/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "outline-variant": "#dbc1ba",
        "surface-variant": "#e4e2de",
        "tertiary-container": "#8e99af",
        "surface": "#fbf9f5",
        "tertiary-fixed": "#d8e3fb",
        "surface-container-low": "#f5f3ef",
        "surface-dim": "#dbdad6",
        "surface-container-highest": "#e4e2de",
        "on-primary-container": "#5d1904",
        "inverse-primary": "#ffb5a0",
        "secondary-fixed": "#e6e6a4",
        "on-surface-variant": "#55433d",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-secondary-fixed-variant": "#484917",
        "surface-tint": "#99452c",
        "on-secondary-fixed": "#1c1d00",
        "on-primary-fixed": "#3b0900",
        "on-error-container": "#93000a",
        "surface-container": "#efeeea",
        "secondary": "#60612c",
        "on-secondary-container": "#646630",
        "on-tertiary-container": "#263143",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#fbf9f5",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#e3e4a2",
        "on-surface": "#1b1c1a",
        "surface-container-high": "#eae8e4",
        "on-primary-fixed-variant": "#7b2e17",
        "on-tertiary-fixed": "#111c2d",
        "inverse-on-surface": "#f2f0ed",
        "primary-container": "#e27d60",
        "outline": "#88726c",
        "error": "#ba1a1a",
        "on-background": "#1b1c1a",
        "secondary-fixed-dim": "#c9ca8b",
        "on-secondary": "#ffffff",
        "inverse-surface": "#30312e",
        "primary": "#99452c",
        "primary-fixed-dim": "#ffb5a0",
        "tertiary": "#545f73",
        "tertiary-fixed-dim": "#bcc7de",
        "primary-fixed": "#ffdbd1",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        serif: ["var(--font-serif)", "serif"],
        brand: ["var(--font-have-heart)", "cursive"],
        script: ["var(--font-dancing)", "cursive"],
        headline: ["var(--font-serif)", "serif"],
        body: ["var(--font-sans)", "sans-serif"],
        label: ["var(--font-sans)", "sans-serif"]
      },
    },
  },
  plugins: [],
};
